name: Build DACPAC

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    env:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: Release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore "${{ env.solution }}"

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build solution
      run: msbuild "${{ env.solution }}" /p:Configuration=${{ env.buildConfiguration }} /p:Platform="${{ env.buildPlatform }}"
  
    - name: Upload DACPAC Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sql-build-artifacts
        path: |
          **/bin/${{ env.buildConfiguration }}/
