name: Build and Deploy SQL Project to Azure SQL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Dacpac
    runs-on: windows-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build DACPAC
      run: msbuild ${{ secrets.PROJECT_PATH }} /p:Configuration=${{ secrets.BUILDCONFIGURATION }} /p:Platform="${{ secrets.BUILDPLATFORM }}" /p:TargetFrameworkVersion=v4.8 /p:DSP=Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: SQLDB
          path: ${{ github.workspace }}/bin/debug/
