name: Build and Deploy SQL Project to Azure SQL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Dacpac
    runs-on: windows-latest

    env:
      solution: '**/*.sln'
      buildConfiguration: Release
      buildPlatform: "Any CPU"
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build DACPAC
      run: msbuild ${{ env.solution }} /p:Configuration=${{ env.buildConfiguration }} /p:Platform="${{ env.buildPlatform }}" /p:TargetFrameworkVersion=v4.8 /p:DSP=Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: SQLDB
          path: ${{ github.workspace }}/bin/debug/
