name: Build and Deploy SQL Project to Azure SQL

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Dacpac
    runs-on: windows-latest
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-version: 'latest'
        
    - name: Execute MSBuild
      run: |
        msbuild smart-campus-portal-db/smart-campus-portal-db.sqlproj /t:Build /p:Configuration=Release /p:DSP="Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider"
      shell: cmd
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SQLDB
        path: ${{secrets.ARTIFACTS_PATH}}./smart-campus-portal-db/bin/Release/*.dacpac
