name: Build and Deploy SQL Project to Azure SQL

on:
  push:
     branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build Dacpac
    runs-on: windows-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build DACPAC
      run: |
          msbuild ${{ secrets.SOLUTION }} /t:Rebuild /p:Configuration=Release /p:DSP=Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider
   
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SQLDB
        path: ${{secrets.ARTIFACTS_PATH}}*.dacpac

  deploy:
    name: DEV
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: SQLDB
          path: dacpac
      
      - name: Deploy to Azure SQL
        uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }} #  Use the connection string secret
          path: 'dacpac/*.dacpac' # Path to the DACPAC file(s)
          action: 'Publish'
