name: Build and Deploy SQL Project to Azure SQL

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Dacpac
    runs-on: windows-latest
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-version: 'latest'

    - name: Download Visual Studio Build Tools Installer
      run: |
        Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile "vs_buildtools.exe"
      shell: powershell

    - name: Install DataBuildTools Workload
      run: |
        Start-Process -Wait -NoNewWindow -FilePath "vs_buildtools.exe" -ArgumentList "--add", "Microsoft.VisualStudio.Workload.DataBuildTools", "--quiet", "--wait", "--norestart"
        Remove-Item "vs_buildtools.exe"
      shell: powershell

    - name: Find SqlPackage.exe
      id: find_sqlpackage
      run: |
        $sqlPackagePath = Get-ChildItem -Path "C:\Program Files*\Microsoft SQL Server\*\DAC\bin\SqlPackage.exe", "C:\Program Files (x86)*\Microsoft SQL Server\*\DAC\bin\SqlPackage.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1 | Select-Object -ExpandProperty FullName
        if ($sqlPackagePath) {
          echo "SQLPACKAGE_PATH=$sqlPackagePath" >> $env:GITHUB_OUTPUT
        } else {
          echo "Error: SqlPackage.exe not found."
          exit 1
        }
      shell: powershell
      
    - name: Execute MSBuild
      run: |
        msbuild smart-campus-portal-db/smart-campus-portal-db.sqlproj /t:Publish /p:Configuration=Release /p:SqlPackageFilePath="${{ steps.find_sqlpackage.outputs.SQLPACKAGE_PATH }}" /p:TargetDACPac="output/SmartCampusServiceDB.dacpac"
      shell: cmd
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SmartCampusServiceDB.dacpac
        path: output/SmartCampusServiceDB.dacpac
