name: Build and Deploy SQL Project to Azure SQL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      solution: '**/*.sln'
      buildConfiguration: Release
      buildPlatform: "Any CPU"
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore ${{ env.solution }}
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build solution
      run: msbuild ${{ env.solution }} /p:Configuration=${{ env.buildConfiguration }} /p:Platform="${{ env.buildPlatform }}"

    - name: Upload .dacpac Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sql-dacpac
        path: '**/bin/${{ env.BUILD_CONFIGURATION }}/*.dacpac'
