name: Build DACPAC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SQL Server Data Tools (SSDT)
      run: |
        Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile "vs_buildtools.exe"
        Start-Process -Wait -NoNewWindow -FilePath "vs_buildtools.exe" -ArgumentList `
          "--add", "Microsoft.VisualStudio.Workload.DataBuildTools", `
          "--quiet", "--norestart", "--wait"
        Remove-Item "vs_buildtools.exe"
      shell: powershell

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-version: 'latest'

    - name: Build DACPAC using MSBuild
      run: |
        msbuild smart-campus-portal-db/smart-campus-portal-db.sqlproj /t:Build /p:Configuration=Release /p:OutputPath=output
      shell: cmd

    - name: Upload DACPAC Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SmartCampusServiceDB.dacpac
        path: output/**/*.dacpac
