name: Build and Deploy SQL Project to Azure SQL

on:
  push:
     branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build Dacpac
    runs-on: windows-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build DACPAC
      run: |
          msbuild SmartCampuSportalDB/SmartCampuSportalDB.sqlproj /t:Rebuild /p:Configuration=Release /p:DSP=Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider
   
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SQLDB
        path: smart-campus-portal-db/bin/Release/*.dacpac
